"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from lcm_msgs import std_msgs
class CompressedImage(object):

    __slots__ = ["data_length", "header", "format", "data"]

    __typenames__ = ["int32_t", "std_msgs.Header", "string", "byte"]

    __dimensions__ = [None, None, None, ["data_length"]]

    def __init__(self):
        self.data_length = 0
        """ LCM Type: int32_t """
        self.header = std_msgs.Header()
        """ LCM Type: std_msgs.Header """
        self.format = ""
        """ LCM Type: string """
        self.data = b""
        """ LCM Type: byte[data_length] """

    def encode(self):
        buf = BytesIO()
        buf.write(CompressedImage._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.data_length))
        assert self.header._get_packed_fingerprint() == std_msgs.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        __format_encoded = self.format.encode('utf-8')
        buf.write(struct.pack('>I', len(__format_encoded)+1))
        buf.write(__format_encoded)
        buf.write(b"\0")
        buf.write(bytearray(self.data[:self.data_length]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != CompressedImage._get_packed_fingerprint():
            raise ValueError("Decode error")
        return CompressedImage._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = CompressedImage()
        self.data_length = struct.unpack(">i", buf.read(4))[0]
        self.header = std_msgs.Header._decode_one(buf)
        __format_len = struct.unpack('>I', buf.read(4))[0]
        self.format = buf.read(__format_len)[:-1].decode('utf-8', 'replace')
        self.data = buf.read(self.data_length)
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if CompressedImage in parents: return 0
        newparents = parents + [CompressedImage]
        tmphash = (0xac8cf79b462311d9+ std_msgs.Header._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if CompressedImage._packed_fingerprint is None:
            CompressedImage._packed_fingerprint = struct.pack(">Q", CompressedImage._get_hash_recursive([]))
        return CompressedImage._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", CompressedImage._get_packed_fingerprint())[0]

