"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from . import *
from .JoyFeedback import JoyFeedback
class JoyFeedbackArray(object):

    __slots__ = ["array_length", "array"]

    __typenames__ = ["int32_t", "JoyFeedback"]

    __dimensions__ = [None, ["array_length"]]

    def __init__(self):
        self.array_length = 0
        """ LCM Type: int32_t """
        self.array = []
        """ LCM Type: JoyFeedback[array_length] """

    def encode(self):
        buf = BytesIO()
        buf.write(JoyFeedbackArray._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.array_length))
        for i0 in range(self.array_length):
            assert self.array[i0]._get_packed_fingerprint() == JoyFeedback._get_packed_fingerprint()
            self.array[i0]._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != JoyFeedbackArray._get_packed_fingerprint():
            raise ValueError("Decode error")
        return JoyFeedbackArray._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = JoyFeedbackArray()
        self.array_length = struct.unpack(">i", buf.read(4))[0]
        self.array = []
        for i0 in range(self.array_length):
            self.array.append(JoyFeedback._decode_one(buf))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if JoyFeedbackArray in parents: return 0
        newparents = parents + [JoyFeedbackArray]
        tmphash = (0xde2a78c20ffefa04+ JoyFeedback._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if JoyFeedbackArray._packed_fingerprint is None:
            JoyFeedbackArray._packed_fingerprint = struct.pack(">Q", JoyFeedbackArray._get_hash_recursive([]))
        return JoyFeedbackArray._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", JoyFeedbackArray._get_packed_fingerprint())[0]

