"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from lcm_msgs import std_msgs
class LaserScan(object):

    __slots__ = ["ranges_length", "intensities_length", "header", "angle_min", "angle_max", "angle_increment", "time_increment", "scan_time", "range_min", "range_max", "ranges", "intensities"]

    __typenames__ = ["int32_t", "int32_t", "std_msgs.Header", "float", "float", "float", "float", "float", "float", "float", "float", "float"]

    __dimensions__ = [None, None, None, None, None, None, None, None, None, None, ["ranges_length"], ["intensities_length"]]

    def __init__(self):
        self.ranges_length = 0
        """ LCM Type: int32_t """
        self.intensities_length = 0
        """ LCM Type: int32_t """
        self.header = std_msgs.Header()
        """ LCM Type: std_msgs.Header """
        self.angle_min = 0.0
        """ LCM Type: float """
        self.angle_max = 0.0
        """ LCM Type: float """
        self.angle_increment = 0.0
        """ LCM Type: float """
        self.time_increment = 0.0
        """ LCM Type: float """
        self.scan_time = 0.0
        """ LCM Type: float """
        self.range_min = 0.0
        """ LCM Type: float """
        self.range_max = 0.0
        """ LCM Type: float """
        self.ranges = []
        """ LCM Type: float[ranges_length] """
        self.intensities = []
        """ LCM Type: float[intensities_length] """

    def encode(self):
        buf = BytesIO()
        buf.write(LaserScan._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ii", self.ranges_length, self.intensities_length))
        assert self.header._get_packed_fingerprint() == std_msgs.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        buf.write(struct.pack(">fffffff", self.angle_min, self.angle_max, self.angle_increment, self.time_increment, self.scan_time, self.range_min, self.range_max))
        buf.write(struct.pack('>%df' % self.ranges_length, *self.ranges[:self.ranges_length]))
        buf.write(struct.pack('>%df' % self.intensities_length, *self.intensities[:self.intensities_length]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != LaserScan._get_packed_fingerprint():
            raise ValueError("Decode error")
        return LaserScan._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = LaserScan()
        self.ranges_length, self.intensities_length = struct.unpack(">ii", buf.read(8))
        self.header = std_msgs.Header._decode_one(buf)
        self.angle_min, self.angle_max, self.angle_increment, self.time_increment, self.scan_time, self.range_min, self.range_max = struct.unpack(">fffffff", buf.read(28))
        self.ranges = struct.unpack('>%df' % self.ranges_length, buf.read(self.ranges_length * 4))
        self.intensities = struct.unpack('>%df' % self.intensities_length, buf.read(self.intensities_length * 4))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if LaserScan in parents: return 0
        newparents = parents + [LaserScan]
        tmphash = (0x1717a961c492e489+ std_msgs.Header._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if LaserScan._packed_fingerprint is None:
            LaserScan._packed_fingerprint = struct.pack(">Q", LaserScan._get_hash_recursive([]))
        return LaserScan._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", LaserScan._get_packed_fingerprint())[0]

