"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from lcm_msgs import std_msgs
class Range(object):

    __slots__ = ["header", "radiation_type", "field_of_view", "min_range", "max_range", "range"]

    __typenames__ = ["std_msgs.Header", "byte", "float", "float", "float", "float"]

    __dimensions__ = [None, None, None, None, None, None]

    ULTRASOUND = 0
    INFRARED = 1

    def __init__(self):
        self.header = std_msgs.Header()
        """ LCM Type: std_msgs.Header """
        self.radiation_type = 0
        """ LCM Type: byte """
        self.field_of_view = 0.0
        """ LCM Type: float """
        self.min_range = 0.0
        """ LCM Type: float """
        self.max_range = 0.0
        """ LCM Type: float """
        self.range = 0.0
        """ LCM Type: float """

    def encode(self):
        buf = BytesIO()
        buf.write(Range._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == std_msgs.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        buf.write(struct.pack(">Bffff", self.radiation_type, self.field_of_view, self.min_range, self.max_range, self.range))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Range._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Range._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = Range()
        self.header = std_msgs.Header._decode_one(buf)
        self.radiation_type, self.field_of_view, self.min_range, self.max_range, self.range = struct.unpack(">Bffff", buf.read(17))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if Range in parents: return 0
        newparents = parents + [Range]
        tmphash = (0xaaf9249a1465f86a+ std_msgs.Header._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if Range._packed_fingerprint is None:
            Range._packed_fingerprint = struct.pack(">Q", Range._get_hash_recursive([]))
        return Range._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", Range._get_packed_fingerprint())[0]

