"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class RegionOfInterest(object):

    __slots__ = ["x_offset", "y_offset", "height", "width", "do_rectify"]

    __typenames__ = ["int32_t", "int32_t", "int32_t", "int32_t", "boolean"]

    __dimensions__ = [None, None, None, None, None]

    def __init__(self):
        self.x_offset = 0
        """ LCM Type: int32_t """
        self.y_offset = 0
        """ LCM Type: int32_t """
        self.height = 0
        """ LCM Type: int32_t """
        self.width = 0
        """ LCM Type: int32_t """
        self.do_rectify = False
        """ LCM Type: boolean """

    def encode(self):
        buf = BytesIO()
        buf.write(RegionOfInterest._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">iiiib", self.x_offset, self.y_offset, self.height, self.width, self.do_rectify))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != RegionOfInterest._get_packed_fingerprint():
            raise ValueError("Decode error")
        return RegionOfInterest._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = RegionOfInterest()
        self.x_offset, self.y_offset, self.height, self.width = struct.unpack(">iiii", buf.read(16))
        self.do_rectify = bool(struct.unpack('b', buf.read(1))[0])
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if RegionOfInterest in parents: return 0
        tmphash = (0x398a869d05983f0e) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if RegionOfInterest._packed_fingerprint is None:
            RegionOfInterest._packed_fingerprint = struct.pack(">Q", RegionOfInterest._get_hash_recursive([]))
        return RegionOfInterest._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", RegionOfInterest._get_packed_fingerprint())[0]

