"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from . import *
from lcm_msgs import std_msgs
from .GoalStatus import GoalStatus
class GoalStatusArray(object):

    __slots__ = ["status_list_length", "header", "status_list"]

    __typenames__ = ["int32_t", "std_msgs.Header", "GoalStatus"]

    __dimensions__ = [None, None, ["status_list_length"]]

    def __init__(self):
        self.status_list_length = 0
        """ LCM Type: int32_t """
        self.header = std_msgs.Header()
        """ LCM Type: std_msgs.Header """
        self.status_list = []
        """ LCM Type: GoalStatus[status_list_length] """

    def encode(self):
        buf = BytesIO()
        buf.write(GoalStatusArray._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.status_list_length))
        assert self.header._get_packed_fingerprint() == std_msgs.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        for i0 in range(self.status_list_length):
            assert self.status_list[i0]._get_packed_fingerprint() == GoalStatus._get_packed_fingerprint()
            self.status_list[i0]._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != GoalStatusArray._get_packed_fingerprint():
            raise ValueError("Decode error")
        return GoalStatusArray._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = GoalStatusArray()
        self.status_list_length = struct.unpack(">i", buf.read(4))[0]
        self.header = std_msgs.Header._decode_one(buf)
        self.status_list = []
        for i0 in range(self.status_list_length):
            self.status_list.append(GoalStatus._decode_one(buf))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if GoalStatusArray in parents: return 0
        newparents = parents + [GoalStatusArray]
        tmphash = (0xf5c35b2e7eed0fa+ std_msgs.Header._get_hash_recursive(newparents)+ GoalStatus._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if GoalStatusArray._packed_fingerprint is None:
            GoalStatusArray._packed_fingerprint = struct.pack(">Q", GoalStatusArray._get_hash_recursive([]))
        return GoalStatusArray._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", GoalStatusArray._get_packed_fingerprint())[0]

