"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from . import *
from lcm_msgs import std_msgs
from .DiagnosticStatus import DiagnosticStatus
class DiagnosticArray(object):

    __slots__ = ["status_length", "header", "status"]

    __typenames__ = ["int32_t", "std_msgs.Header", "DiagnosticStatus"]

    __dimensions__ = [None, None, ["status_length"]]

    def __init__(self):
        self.status_length = 0
        """ LCM Type: int32_t """
        self.header = std_msgs.Header()
        """ LCM Type: std_msgs.Header """
        self.status = []
        """ LCM Type: DiagnosticStatus[status_length] """

    def encode(self):
        buf = BytesIO()
        buf.write(DiagnosticArray._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.status_length))
        assert self.header._get_packed_fingerprint() == std_msgs.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        for i0 in range(self.status_length):
            assert self.status[i0]._get_packed_fingerprint() == DiagnosticStatus._get_packed_fingerprint()
            self.status[i0]._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != DiagnosticArray._get_packed_fingerprint():
            raise ValueError("Decode error")
        return DiagnosticArray._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = DiagnosticArray()
        self.status_length = struct.unpack(">i", buf.read(4))[0]
        self.header = std_msgs.Header._decode_one(buf)
        self.status = []
        for i0 in range(self.status_length):
            self.status.append(DiagnosticStatus._decode_one(buf))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if DiagnosticArray in parents: return 0
        newparents = parents + [DiagnosticArray]
        tmphash = (0x163c308c500b94d+ std_msgs.Header._get_hash_recursive(newparents)+ DiagnosticStatus._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if DiagnosticArray._packed_fingerprint is None:
            DiagnosticArray._packed_fingerprint = struct.pack(">Q", DiagnosticArray._get_hash_recursive([]))
        return DiagnosticArray._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", DiagnosticArray._get_packed_fingerprint())[0]

