"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from . import *
from .Accel import Accel
class AccelWithCovariance(object):

    __slots__ = ["accel", "covariance"]

    __typenames__ = ["Accel", "double"]

    __dimensions__ = [None, [36]]

    def __init__(self):
        self.accel = Accel()
        """ LCM Type: Accel """
        self.covariance = [ 0.0 for dim0 in range(36) ]
        """ LCM Type: double[36] """

    def encode(self):
        buf = BytesIO()
        buf.write(AccelWithCovariance._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.accel._get_packed_fingerprint() == Accel._get_packed_fingerprint()
        self.accel._encode_one(buf)
        buf.write(struct.pack('>36d', *self.covariance[:36]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != AccelWithCovariance._get_packed_fingerprint():
            raise ValueError("Decode error")
        return AccelWithCovariance._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = AccelWithCovariance()
        self.accel = Accel._decode_one(buf)
        self.covariance = struct.unpack('>36d', buf.read(288))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if AccelWithCovariance in parents: return 0
        newparents = parents + [AccelWithCovariance]
        tmphash = (0x545f576dfe97951d+ Accel._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if AccelWithCovariance._packed_fingerprint is None:
            AccelWithCovariance._packed_fingerprint = struct.pack(">Q", AccelWithCovariance._get_hash_recursive([]))
        return AccelWithCovariance._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", AccelWithCovariance._get_packed_fingerprint())[0]

