"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from . import *
from .Point32 import Point32
class Polygon(object):

    __slots__ = ["points_length", "points"]

    __typenames__ = ["int32_t", "Point32"]

    __dimensions__ = [None, ["points_length"]]

    def __init__(self):
        self.points_length = 0
        """ LCM Type: int32_t """
        self.points = []
        """ LCM Type: Point32[points_length] """

    def encode(self):
        buf = BytesIO()
        buf.write(Polygon._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.points_length))
        for i0 in range(self.points_length):
            assert self.points[i0]._get_packed_fingerprint() == Point32._get_packed_fingerprint()
            self.points[i0]._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Polygon._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Polygon._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = Polygon()
        self.points_length = struct.unpack(">i", buf.read(4))[0]
        self.points = []
        for i0 in range(self.points_length):
            self.points.append(Point32._decode_one(buf))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if Polygon in parents: return 0
        newparents = parents + [Polygon]
        tmphash = (0x5634733b354407e8+ Point32._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if Polygon._packed_fingerprint is None:
            Polygon._packed_fingerprint = struct.pack(">Q", Polygon._get_hash_recursive([]))
        return Polygon._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", Polygon._get_packed_fingerprint())[0]

