"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from . import *
from lcm_msgs import std_msgs
from .Pose import Pose
class PoseStamped(object):

    __slots__ = ["header", "pose"]

    __typenames__ = ["std_msgs.Header", "Pose"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.header = std_msgs.Header()
        """ LCM Type: std_msgs.Header """
        self.pose = Pose()
        """ LCM Type: Pose """

    def encode(self):
        buf = BytesIO()
        buf.write(PoseStamped._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == std_msgs.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        assert self.pose._get_packed_fingerprint() == Pose._get_packed_fingerprint()
        self.pose._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != PoseStamped._get_packed_fingerprint():
            raise ValueError("Decode error")
        return PoseStamped._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = PoseStamped()
        self.header = std_msgs.Header._decode_one(buf)
        self.pose = Pose._decode_one(buf)
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if PoseStamped in parents: return 0
        newparents = parents + [PoseStamped]
        tmphash = (0xe10feebec5c97663+ std_msgs.Header._get_hash_recursive(newparents)+ Pose._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if PoseStamped._packed_fingerprint is None:
            PoseStamped._packed_fingerprint = struct.pack(">Q", PoseStamped._get_hash_recursive([]))
        return PoseStamped._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", PoseStamped._get_packed_fingerprint())[0]

