"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from . import *
from lcm_msgs import std_msgs
from .Quaternion import Quaternion
class QuaternionStamped(object):

    __slots__ = ["header", "quaternion"]

    __typenames__ = ["std_msgs.Header", "Quaternion"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.header = std_msgs.Header()
        """ LCM Type: std_msgs.Header """
        self.quaternion = Quaternion()
        """ LCM Type: Quaternion """

    def encode(self):
        buf = BytesIO()
        buf.write(QuaternionStamped._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == std_msgs.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        assert self.quaternion._get_packed_fingerprint() == Quaternion._get_packed_fingerprint()
        self.quaternion._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != QuaternionStamped._get_packed_fingerprint():
            raise ValueError("Decode error")
        return QuaternionStamped._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = QuaternionStamped()
        self.header = std_msgs.Header._decode_one(buf)
        self.quaternion = Quaternion._decode_one(buf)
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if QuaternionStamped in parents: return 0
        newparents = parents + [QuaternionStamped]
        tmphash = (0x7a3833b23af3ee48+ std_msgs.Header._get_hash_recursive(newparents)+ Quaternion._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if QuaternionStamped._packed_fingerprint is None:
            QuaternionStamped._packed_fingerprint = struct.pack(">Q", QuaternionStamped._get_hash_recursive([]))
        return QuaternionStamped._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", QuaternionStamped._get_packed_fingerprint())[0]

