"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from . import *
from .FrameTransform import FrameTransform
class FrameTransforms(object):

    __slots__ = ["transforms_length", "transforms"]

    __typenames__ = ["int32_t", "FrameTransform"]

    __dimensions__ = [None, ["transforms_length"]]

    def __init__(self):
        self.transforms_length = 0
        """ LCM Type: int32_t """
        self.transforms = []
        """ LCM Type: FrameTransform[transforms_length] """

    def encode(self):
        buf = BytesIO()
        buf.write(FrameTransforms._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.transforms_length))
        for i0 in range(self.transforms_length):
            assert self.transforms[i0]._get_packed_fingerprint() == FrameTransform._get_packed_fingerprint()
            self.transforms[i0]._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != FrameTransforms._get_packed_fingerprint():
            raise ValueError("Decode error")
        return FrameTransforms._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = FrameTransforms()
        self.transforms_length = struct.unpack(">i", buf.read(4))[0]
        self.transforms = []
        for i0 in range(self.transforms_length):
            self.transforms.append(FrameTransform._decode_one(buf))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if FrameTransforms in parents: return 0
        newparents = parents + [FrameTransforms]
        tmphash = (0x37bc5cbce50a5ce2+ FrameTransform._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if FrameTransforms._packed_fingerprint is None:
            FrameTransforms._packed_fingerprint = struct.pack(">Q", FrameTransforms._get_hash_recursive([]))
        return FrameTransforms._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", FrameTransforms._get_packed_fingerprint())[0]

