"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from lcm_msgs import geometry_msgs
from lcm_msgs import builtin_interfaces
class FrameTransform(object):

    __slots__ = ["timestamp", "parent_frame_id", "child_frame_id", "translation", "rotation"]

    __typenames__ = ["builtin_interfaces.Time", "string", "string", "geometry_msgs.Vector3", "geometry_msgs.Quaternion"]

    __dimensions__ = [None, None, None, None, None]

    def __init__(self):
        self.timestamp = builtin_interfaces.Time()
        """ LCM Type: builtin_interfaces.Time """
        self.parent_frame_id = ""
        """ LCM Type: string """
        self.child_frame_id = ""
        """ LCM Type: string """
        self.translation = geometry_msgs.Vector3()
        """ LCM Type: geometry_msgs.Vector3 """
        self.rotation = geometry_msgs.Quaternion()
        """ LCM Type: geometry_msgs.Quaternion """

    def encode(self):
        buf = BytesIO()
        buf.write(FrameTransform._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.timestamp._get_packed_fingerprint() == builtin_interfaces.Time._get_packed_fingerprint()
        self.timestamp._encode_one(buf)
        __parent_frame_id_encoded = self.parent_frame_id.encode('utf-8')
        buf.write(struct.pack('>I', len(__parent_frame_id_encoded)+1))
        buf.write(__parent_frame_id_encoded)
        buf.write(b"\0")
        __child_frame_id_encoded = self.child_frame_id.encode('utf-8')
        buf.write(struct.pack('>I', len(__child_frame_id_encoded)+1))
        buf.write(__child_frame_id_encoded)
        buf.write(b"\0")
        assert self.translation._get_packed_fingerprint() == geometry_msgs.Vector3._get_packed_fingerprint()
        self.translation._encode_one(buf)
        assert self.rotation._get_packed_fingerprint() == geometry_msgs.Quaternion._get_packed_fingerprint()
        self.rotation._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != FrameTransform._get_packed_fingerprint():
            raise ValueError("Decode error")
        return FrameTransform._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = FrameTransform()
        self.timestamp = builtin_interfaces.Time._decode_one(buf)
        __parent_frame_id_len = struct.unpack('>I', buf.read(4))[0]
        self.parent_frame_id = buf.read(__parent_frame_id_len)[:-1].decode('utf-8', 'replace')
        __child_frame_id_len = struct.unpack('>I', buf.read(4))[0]
        self.child_frame_id = buf.read(__child_frame_id_len)[:-1].decode('utf-8', 'replace')
        self.translation = geometry_msgs.Vector3._decode_one(buf)
        self.rotation = geometry_msgs.Quaternion._decode_one(buf)
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if FrameTransform in parents: return 0
        newparents = parents + [FrameTransform]
        tmphash = (0x16cb223d6329d1f0+ builtin_interfaces.Time._get_hash_recursive(newparents)+ geometry_msgs.Vector3._get_hash_recursive(newparents)+ geometry_msgs.Quaternion._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if FrameTransform._packed_fingerprint is None:
            FrameTransform._packed_fingerprint = struct.pack(">Q", FrameTransform._get_hash_recursive([]))
        return FrameTransform._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", FrameTransform._get_packed_fingerprint())[0]

