"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class GeoJSON(object):

    __slots__ = ["geojson"]

    __typenames__ = ["string"]

    __dimensions__ = [None]

    def __init__(self):
        self.geojson = ""
        """ LCM Type: string """

    def encode(self):
        buf = BytesIO()
        buf.write(GeoJSON._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __geojson_encoded = self.geojson.encode('utf-8')
        buf.write(struct.pack('>I', len(__geojson_encoded)+1))
        buf.write(__geojson_encoded)
        buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != GeoJSON._get_packed_fingerprint():
            raise ValueError("Decode error")
        return GeoJSON._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = GeoJSON()
        __geojson_len = struct.unpack('>I', buf.read(4))[0]
        self.geojson = buf.read(__geojson_len)[:-1].decode('utf-8', 'replace')
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if GeoJSON in parents: return 0
        tmphash = (0x15423f51794b2ebc) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if GeoJSON._packed_fingerprint is None:
            GeoJSON._packed_fingerprint = struct.pack(">Q", GeoJSON._get_hash_recursive([]))
        return GeoJSON._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", GeoJSON._get_packed_fingerprint())[0]

