"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class PackedElementField(object):

    __slots__ = ["name", "offset", "type"]

    __typenames__ = ["string", "int32_t", "byte"]

    __dimensions__ = [None, None, None]

    UNKNOWN = 0
    UINT8 = 1
    INT8 = 2
    UINT16 = 3
    INT16 = 4
    UINT32 = 5
    INT32 = 6
    FLOAT32 = 7
    FLOAT64 = 8

    def __init__(self):
        self.name = ""
        """ LCM Type: string """
        self.offset = 0
        """ LCM Type: int32_t """
        self.type = 0
        """ LCM Type: byte """

    def encode(self):
        buf = BytesIO()
        buf.write(PackedElementField._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">iB", self.offset, self.type))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != PackedElementField._get_packed_fingerprint():
            raise ValueError("Decode error")
        return PackedElementField._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = PackedElementField()
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        self.offset, self.type = struct.unpack(">iB", buf.read(5))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if PackedElementField in parents: return 0
        tmphash = (0x47c85ba0fafa16b8) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if PackedElementField._packed_fingerprint is None:
            PackedElementField._packed_fingerprint = struct.pack(">Q", PackedElementField._get_hash_recursive([]))
        return PackedElementField._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", PackedElementField._get_packed_fingerprint())[0]

