"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from lcm_msgs import geometry_msgs
from lcm_msgs import builtin_interfaces
class PoseInFrame(object):

    __slots__ = ["timestamp", "frame_id", "pose"]

    __typenames__ = ["builtin_interfaces.Time", "string", "geometry_msgs.Pose"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.timestamp = builtin_interfaces.Time()
        """ LCM Type: builtin_interfaces.Time """
        self.frame_id = ""
        """ LCM Type: string """
        self.pose = geometry_msgs.Pose()
        """ LCM Type: geometry_msgs.Pose """

    def encode(self):
        buf = BytesIO()
        buf.write(PoseInFrame._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.timestamp._get_packed_fingerprint() == builtin_interfaces.Time._get_packed_fingerprint()
        self.timestamp._encode_one(buf)
        __frame_id_encoded = self.frame_id.encode('utf-8')
        buf.write(struct.pack('>I', len(__frame_id_encoded)+1))
        buf.write(__frame_id_encoded)
        buf.write(b"\0")
        assert self.pose._get_packed_fingerprint() == geometry_msgs.Pose._get_packed_fingerprint()
        self.pose._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != PoseInFrame._get_packed_fingerprint():
            raise ValueError("Decode error")
        return PoseInFrame._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = PoseInFrame()
        self.timestamp = builtin_interfaces.Time._decode_one(buf)
        __frame_id_len = struct.unpack('>I', buf.read(4))[0]
        self.frame_id = buf.read(__frame_id_len)[:-1].decode('utf-8', 'replace')
        self.pose = geometry_msgs.Pose._decode_one(buf)
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if PoseInFrame in parents: return 0
        newparents = parents + [PoseInFrame]
        tmphash = (0x84c6ef3a0a4c5cd6+ builtin_interfaces.Time._get_hash_recursive(newparents)+ geometry_msgs.Pose._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if PoseInFrame._packed_fingerprint is None:
            PoseInFrame._packed_fingerprint = struct.pack(">Q", PoseInFrame._get_hash_recursive([]))
        return PoseInFrame._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", PoseInFrame._get_packed_fingerprint())[0]

