"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from lcm_msgs import builtin_interfaces
class SceneEntityDeletion(object):

    __slots__ = ["timestamp", "type", "id"]

    __typenames__ = ["builtin_interfaces.Time", "byte", "string"]

    __dimensions__ = [None, None, None]

    MATCHING_ID = 0
    ALL = 1

    def __init__(self):
        self.timestamp = builtin_interfaces.Time()
        """ LCM Type: builtin_interfaces.Time """
        self.type = 0
        """ LCM Type: byte """
        self.id = ""
        """ LCM Type: string """

    def encode(self):
        buf = BytesIO()
        buf.write(SceneEntityDeletion._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.timestamp._get_packed_fingerprint() == builtin_interfaces.Time._get_packed_fingerprint()
        self.timestamp._encode_one(buf)
        buf.write(struct.pack(">B", self.type))
        __id_encoded = self.id.encode('utf-8')
        buf.write(struct.pack('>I', len(__id_encoded)+1))
        buf.write(__id_encoded)
        buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != SceneEntityDeletion._get_packed_fingerprint():
            raise ValueError("Decode error")
        return SceneEntityDeletion._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = SceneEntityDeletion()
        self.timestamp = builtin_interfaces.Time._decode_one(buf)
        self.type = struct.unpack(">B", buf.read(1))[0]
        __id_len = struct.unpack('>I', buf.read(4))[0]
        self.id = buf.read(__id_len)[:-1].decode('utf-8', 'replace')
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if SceneEntityDeletion in parents: return 0
        newparents = parents + [SceneEntityDeletion]
        tmphash = (0xa6b01fa4694da548+ builtin_interfaces.Time._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if SceneEntityDeletion._packed_fingerprint is None:
            SceneEntityDeletion._packed_fingerprint = struct.pack(">Q", SceneEntityDeletion._get_hash_recursive([]))
        return SceneEntityDeletion._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", SceneEntityDeletion._get_packed_fingerprint())[0]

