"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from . import *
from .InteractiveMarker import InteractiveMarker
class InteractiveMarkerInit(object):

    __slots__ = ["markers_length", "server_id", "seq_num", "markers"]

    __typenames__ = ["int32_t", "string", "int64_t", "InteractiveMarker"]

    __dimensions__ = [None, None, None, ["markers_length"]]

    def __init__(self):
        self.markers_length = 0
        """ LCM Type: int32_t """
        self.server_id = ""
        """ LCM Type: string """
        self.seq_num = 0
        """ LCM Type: int64_t """
        self.markers = []
        """ LCM Type: InteractiveMarker[markers_length] """

    def encode(self):
        buf = BytesIO()
        buf.write(InteractiveMarkerInit._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.markers_length))
        __server_id_encoded = self.server_id.encode('utf-8')
        buf.write(struct.pack('>I', len(__server_id_encoded)+1))
        buf.write(__server_id_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">q", self.seq_num))
        for i0 in range(self.markers_length):
            assert self.markers[i0]._get_packed_fingerprint() == InteractiveMarker._get_packed_fingerprint()
            self.markers[i0]._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != InteractiveMarkerInit._get_packed_fingerprint():
            raise ValueError("Decode error")
        return InteractiveMarkerInit._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = InteractiveMarkerInit()
        self.markers_length = struct.unpack(">i", buf.read(4))[0]
        __server_id_len = struct.unpack('>I', buf.read(4))[0]
        self.server_id = buf.read(__server_id_len)[:-1].decode('utf-8', 'replace')
        self.seq_num = struct.unpack(">q", buf.read(8))[0]
        self.markers = []
        for i0 in range(self.markers_length):
            self.markers.append(InteractiveMarker._decode_one(buf))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if InteractiveMarkerInit in parents: return 0
        newparents = parents + [InteractiveMarkerInit]
        tmphash = (0xd2afaf11cff61d9+ InteractiveMarker._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if InteractiveMarkerInit._packed_fingerprint is None:
            InteractiveMarkerInit._packed_fingerprint = struct.pack(">Q", InteractiveMarkerInit._get_hash_recursive([]))
        return InteractiveMarkerInit._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", InteractiveMarkerInit._get_packed_fingerprint())[0]

