"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from . import *
from .Marker import Marker
class MarkerArray(object):

    __slots__ = ["markers_length", "markers"]

    __typenames__ = ["int32_t", "Marker"]

    __dimensions__ = [None, ["markers_length"]]

    def __init__(self):
        self.markers_length = 0
        """ LCM Type: int32_t """
        self.markers = []
        """ LCM Type: Marker[markers_length] """

    def encode(self):
        buf = BytesIO()
        buf.write(MarkerArray._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.markers_length))
        for i0 in range(self.markers_length):
            assert self.markers[i0]._get_packed_fingerprint() == Marker._get_packed_fingerprint()
            self.markers[i0]._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != MarkerArray._get_packed_fingerprint():
            raise ValueError("Decode error")
        return MarkerArray._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = MarkerArray()
        self.markers_length = struct.unpack(">i", buf.read(4))[0]
        self.markers = []
        for i0 in range(self.markers_length):
            self.markers.append(Marker._decode_one(buf))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if MarkerArray in parents: return 0
        newparents = parents + [MarkerArray]
        tmphash = (0xd9e3851dad1e0d9e+ Marker._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if MarkerArray._packed_fingerprint is None:
            MarkerArray._packed_fingerprint = struct.pack(">Q", MarkerArray._get_hash_recursive([]))
        return MarkerArray._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", MarkerArray._get_packed_fingerprint())[0]

