"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class Float64(object):

    __slots__ = ["data"]

    __typenames__ = ["double"]

    __dimensions__ = [None]

    def __init__(self):
        self.data = 0.0
        """ LCM Type: double """

    def encode(self):
        buf = BytesIO()
        buf.write(Float64._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">d", self.data))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Float64._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Float64._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = Float64()
        self.data = struct.unpack(">d", buf.read(8))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if Float64 in parents: return 0
        tmphash = (0x90eea081d4d0b10a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if Float64._packed_fingerprint is None:
            Float64._packed_fingerprint = struct.pack(">Q", Float64._get_hash_recursive([]))
        return Float64._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", Float64._get_packed_fingerprint())[0]

