"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class Int32(object):

    __slots__ = ["data"]

    __typenames__ = ["int32_t"]

    __dimensions__ = [None]

    def __init__(self):
        self.data = 0
        """ LCM Type: int32_t """

    def encode(self):
        buf = BytesIO()
        buf.write(Int32._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.data))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Int32._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Int32._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = Int32()
        self.data = struct.unpack(">i", buf.read(4))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if Int32 in parents: return 0
        tmphash = (0x165e7cfbf548811f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if Int32._packed_fingerprint is None:
            Int32._packed_fingerprint = struct.pack(">Q", Int32._get_hash_recursive([]))
        return Int32._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", Int32._get_packed_fingerprint())[0]

