"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from . import *
from .MultiArrayDimension import MultiArrayDimension
class MultiArrayLayout(object):

    __slots__ = ["dim_length", "dim", "data_offset"]

    __typenames__ = ["int32_t", "MultiArrayDimension", "int32_t"]

    __dimensions__ = [None, ["dim_length"], None]

    def __init__(self):
        self.dim_length = 0
        """ LCM Type: int32_t """
        self.dim = []
        """ LCM Type: MultiArrayDimension[dim_length] """
        self.data_offset = 0
        """ LCM Type: int32_t """

    def encode(self):
        buf = BytesIO()
        buf.write(MultiArrayLayout._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.dim_length))
        for i0 in range(self.dim_length):
            assert self.dim[i0]._get_packed_fingerprint() == MultiArrayDimension._get_packed_fingerprint()
            self.dim[i0]._encode_one(buf)
        buf.write(struct.pack(">i", self.data_offset))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != MultiArrayLayout._get_packed_fingerprint():
            raise ValueError("Decode error")
        return MultiArrayLayout._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = MultiArrayLayout()
        self.dim_length = struct.unpack(">i", buf.read(4))[0]
        self.dim = []
        for i0 in range(self.dim_length):
            self.dim.append(MultiArrayDimension._decode_one(buf))
        self.data_offset = struct.unpack(">i", buf.read(4))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if MultiArrayLayout in parents: return 0
        newparents = parents + [MultiArrayLayout]
        tmphash = (0xbf4b5363481d321+ MultiArrayDimension._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if MultiArrayLayout._packed_fingerprint is None:
            MultiArrayLayout._packed_fingerprint = struct.pack(">Q", MultiArrayLayout._get_hash_recursive([]))
        return MultiArrayLayout._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", MultiArrayLayout._get_packed_fingerprint())[0]

