"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class MultiArrayDimension(object):

    __slots__ = ["label", "size", "stride"]

    __typenames__ = ["string", "int32_t", "int32_t"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.label = ""
        """ LCM Type: string """
        self.size = 0
        """ LCM Type: int32_t """
        self.stride = 0
        """ LCM Type: int32_t """

    def encode(self):
        buf = BytesIO()
        buf.write(MultiArrayDimension._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __label_encoded = self.label.encode('utf-8')
        buf.write(struct.pack('>I', len(__label_encoded)+1))
        buf.write(__label_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">ii", self.size, self.stride))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != MultiArrayDimension._get_packed_fingerprint():
            raise ValueError("Decode error")
        return MultiArrayDimension._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = MultiArrayDimension()
        __label_len = struct.unpack('>I', buf.read(4))[0]
        self.label = buf.read(__label_len)[:-1].decode('utf-8', 'replace')
        self.size, self.stride = struct.unpack(">ii", buf.read(8))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if MultiArrayDimension in parents: return 0
        tmphash = (0xcec1b9e9d868ef97) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if MultiArrayDimension._packed_fingerprint is None:
            MultiArrayDimension._packed_fingerprint = struct.pack(">Q", MultiArrayDimension._get_hash_recursive([]))
        return MultiArrayDimension._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", MultiArrayDimension._get_packed_fingerprint())[0]

