"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from . import *
from .MultiArrayLayout import MultiArrayLayout
class UInt8MultiArray(object):

    __slots__ = ["data_length", "layout", "data"]

    __typenames__ = ["int32_t", "MultiArrayLayout", "byte"]

    __dimensions__ = [None, None, ["data_length"]]

    def __init__(self):
        self.data_length = 0
        """ LCM Type: int32_t """
        self.layout = MultiArrayLayout()
        """ LCM Type: MultiArrayLayout """
        self.data = b""
        """ LCM Type: byte[data_length] """

    def encode(self):
        buf = BytesIO()
        buf.write(UInt8MultiArray._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.data_length))
        assert self.layout._get_packed_fingerprint() == MultiArrayLayout._get_packed_fingerprint()
        self.layout._encode_one(buf)
        buf.write(bytearray(self.data[:self.data_length]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != UInt8MultiArray._get_packed_fingerprint():
            raise ValueError("Decode error")
        return UInt8MultiArray._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = UInt8MultiArray()
        self.data_length = struct.unpack(">i", buf.read(4))[0]
        self.layout = MultiArrayLayout._decode_one(buf)
        self.data = buf.read(self.data_length)
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if UInt8MultiArray in parents: return 0
        newparents = parents + [UInt8MultiArray]
        tmphash = (0x386aefa0332516bf+ MultiArrayLayout._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if UInt8MultiArray._packed_fingerprint is None:
            UInt8MultiArray._packed_fingerprint = struct.pack(">Q", UInt8MultiArray._get_hash_recursive([]))
        return UInt8MultiArray._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", UInt8MultiArray._get_packed_fingerprint())[0]

