"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from lcm_msgs import geometry_msgs
from lcm_msgs import std_msgs
class Odometry(object):

    __slots__ = ["header", "child_frame_id", "pose", "twist"]

    __typenames__ = ["std_msgs.Header", "string", "geometry_msgs.PoseWithCovariance", "geometry_msgs.TwistWithCovariance"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.header = std_msgs.Header()
        """ LCM Type: std_msgs.Header """
        self.child_frame_id = ""
        """ LCM Type: string """
        self.pose = geometry_msgs.PoseWithCovariance()
        """ LCM Type: geometry_msgs.PoseWithCovariance """
        self.twist = geometry_msgs.TwistWithCovariance()
        """ LCM Type: geometry_msgs.TwistWithCovariance """

    def encode(self):
        buf = BytesIO()
        buf.write(Odometry._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == std_msgs.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        __child_frame_id_encoded = self.child_frame_id.encode('utf-8')
        buf.write(struct.pack('>I', len(__child_frame_id_encoded)+1))
        buf.write(__child_frame_id_encoded)
        buf.write(b"\0")
        assert self.pose._get_packed_fingerprint() == geometry_msgs.PoseWithCovariance._get_packed_fingerprint()
        self.pose._encode_one(buf)
        assert self.twist._get_packed_fingerprint() == geometry_msgs.TwistWithCovariance._get_packed_fingerprint()
        self.twist._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Odometry._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Odometry._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = Odometry()
        self.header = std_msgs.Header._decode_one(buf)
        __child_frame_id_len = struct.unpack('>I', buf.read(4))[0]
        self.child_frame_id = buf.read(__child_frame_id_len)[:-1].decode('utf-8', 'replace')
        self.pose = geometry_msgs.PoseWithCovariance._decode_one(buf)
        self.twist = geometry_msgs.TwistWithCovariance._decode_one(buf)
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if Odometry in parents: return 0
        newparents = parents + [Odometry]
        tmphash = (0x97f82279756d9d18+ std_msgs.Header._get_hash_recursive(newparents)+ geometry_msgs.PoseWithCovariance._get_hash_recursive(newparents)+ geometry_msgs.TwistWithCovariance._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if Odometry._packed_fingerprint is None:
            Odometry._packed_fingerprint = struct.pack(">Q", Odometry._get_hash_recursive([]))
        return Odometry._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", Odometry._get_packed_fingerprint())[0]

